In [1]:
item_list = ['Bread', 'Milk', 'Eggs', 'Butter', 'Cocoa']
student_marks = [78, 47, 96, 55, 34]
hetero_list = [ 1,2,3.0, 'text', True, 3+2j ]
print(hetero_list)

[1, 2, 3.0, 'text', True, (3+2j)]


In [7]:
student_marks = [78, 47, 96, 55, 34]
for i in range(len(student_marks)):
    student_marks[i]+=5
print(student_marks)

[83, 52, 101, 60, 39]


In [9]:
%%time
list1 = list(range(1,1000000))
list2 = list(range(2,1000001))
list3 = []
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])

CPU times: total: 609 ms
Wall time: 687 ms


In [4]:
import numpy as np
student_marks_arr = np.array([78, 92, 36, 64, 89])
student_marks_arr

array([78, 92, 36, 64, 89])

In [11]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr

array([[ 18,  15,  18,  16,  17],
       [130, 165, 150, 150, 140],
       [307, 350, 318, 304, 302]])

In [12]:
car_attributes_arr.shape

(3, 5)

In [13]:
car_attributes_arr.dtype

dtype('int32')

In [14]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes, dtype = 'float')
print(car_attributes_arr)
print(car_attributes_arr.dtype)

[[ 18.  15.  18.  16.  17.]
 [130. 165. 150. 150. 140.]
 [307. 350. 318. 304. 302.]]
float64


In [15]:
cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
cars[1]

'buick skylark 320'

In [9]:
car_names=['chevorlet','buick','ply','amc','ford']
horsepower=[130,165,150,150,140]
car_hp_arr=np.array([car_names,horsepower])
car_hp_arr

array([['chevorlet', 'buick', 'ply', 'amc', 'ford'],
       ['130', '165', '150', '150', '140']], dtype='<U11')

In [10]:
car_hp_arr[0]

array(['chevorlet', 'buick', 'ply', 'amc', 'ford'], dtype='<U11')

In [11]:
car_hp_arr[1]

array(['130', '165', '150', '150', '140'], dtype='<U11')

In [12]:
car_hp_arr[0,1]

'buick'

In [13]:
car_hp_arr[0,-2]

'amc'

In [14]:
cars = np.array(['chevrolet', 'buick', 'ply', 'amc', 'ford'])
cars[1:4]

array(['buick', 'ply', 'amc'], dtype='<U9')

In [15]:
car_names = ['chevrolet', 'buick', 'ply', 'amc', 'ford']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr

array([['chevrolet', 'buick', 'ply', 'amc', 'ford'],
       ['130', '165', '150', '150', '140'],
       ['18', '15', '18', '16', '17']], dtype='<U11')

In [16]:
car_hp_acc_arr[0:3]

array([['chevrolet', 'buick', 'ply', 'amc', 'ford'],
       ['130', '165', '150', '150', '140'],
       ['18', '15', '18', '16', '17']], dtype='<U11')

In [17]:
car_hp_acc_arr[0:2, 3:5]

array([['amc', 'ford'],
       ['150', '140']], dtype='<U11')

In [18]:
car_hp_acc_arr[0:3, 0:3]

array([['chevrolet', 'buick', 'ply'],
       ['130', '165', '150'],
       ['18', '15', '18']], dtype='<U11')

In [21]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("Mean horsepower = ",np.mean(horsepower_arr))

Mean horsepower =  147.0


In [22]:
print("Minimum horsepower: ", np.min(horsepower_arr))
print("Maximum horsepower: ", np.max(horsepower_arr))

Minimum horsepower:  130
Maximum horsepower:  165


In [23]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("Index of Minimum horsepower: ", np.argmin(horsepower_arr))
print("Index of Maximum horsepower: ", np.argmax(horsepower_arr))

Index of Minimum horsepower:  0
Index of Maximum horsepower:  1


In [24]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
x = np.where(horsepower_arr >= 150)
print(x)
horsepower_arr[x]

(array([1, 2, 3], dtype=int64),)


array([165, 150, 150])

In [25]:
horsepower_arr[3]

150

In [26]:
horsepower_arr[[1,4]]

array([165, 140])

In [27]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
x = horsepower_arr > 135
print(x.dtype)
newarr = horsepower_arr[x]
print(x)
print(newarr)

bool
[False  True  True  True  True]
[165 150 150 140]


In [28]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
#using sort(array)
print('original array: ', horsepower_arr)
print('Sorted array: ', np.sort(horsepower_arr))
print('original array after sorting: ', horsepower_arr)
sortedarray = np.sort(horsepower_arr)
print(sortedarray)

original array:  [130 165 150 150 140]
Sorted array:  [130 140 150 150 165]
original array after sorting:  [130 165 150 150 140]
[130 140 150 150 165]


In [30]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
np.sort(horsepower_arr)
print(horsepower_arr)
horsepower_arr.sort()
print(horsepower_arr)

[130 165 150 150 140]
[130 140 150 150 165]


In [31]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print('original array: ', horsepower_arr)
horsepower_arr.sort()
print('original array after sorting: ', horsepower_arr)


original array:  [130 165 150 150 140]
original array after sorting:  [130 140 150 150 165]


In [32]:
student_marks_arr = np.array([78, 92, 36, 64, 89])
print(np.sum(student_marks_arr))

359


In [34]:
additional_marks = [2, 2, 5, 10, 1]
student_marks_arr =student_marks_arr+additional_marks
student_marks_arr

array([80, 94, 41, 74, 90])

In [35]:
student_marks_arr = np.array([78, 92, 36, 64, 89])
student_marks_arr = np.add(student_marks_arr, additional_marks)
student_marks_arr

array([80, 94, 41, 74, 90])

In [36]:
array1=np.array([5, 10, 15])
array2=np.array([5])
array3= array1 * array2
array3

array([25, 50, 75])

In [37]:
array1=np.array([0,1,2])
array2=np.array([5])
array3= array1 + array2
array3

array([5, 6, 7])

In [38]:
array1=np.array([[1,1,1],[1,1,1],[1,1,1]])
array2=np.array([0,1,2])
array3= array1 + array2
array3

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [39]:
students_marks = np.array([[67, 45],[90, 92],[66, 72],[32, 40]])
students_marks

array([[67, 45],
       [90, 92],
       [66, 72],
       [32, 40]])

In [40]:
students_marks += [5,10]
students_marks

array([[ 72,  55],
       [ 95, 102],
       [ 71,  82],
       [ 37,  50]])

In [44]:
np.arange(0,10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [45]:
np.arange(1,12,3)

array([ 1,  4,  7, 10])

In [46]:
arr = np.linspace(0,10,5)
print(arr)
print('Length of arr: ',len(arr))

[ 0.   2.5  5.   7.5 10. ]
Length of arr:  5


In [47]:
print(np.linspace(0,10,3))

[ 0.  5. 10.]


In [48]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
np.ones(3)

array([1., 1., 1.])

In [51]:
np.ones([2,1])

array([[1.],
       [1.]])

In [52]:
np.full(5,8)

array([8, 8, 8, 8, 8])

In [53]:
np.full([3,3],10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [54]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [55]:
np.random.rand(5)

array([0.98654733, 0.55688633, 0.51613337, 0.24955166, 0.17514237])

In [56]:
np.random.randint(1,10, size=5)

array([1, 3, 8, 7, 6])

In [57]:
x = np.random.randint(20,30, size=(3, 5))
print(x)
print(type(x))

[[20 28 20 25 23]
 [25 24 21 21 26]
 [20 24 22 28 26]]
<class 'numpy.ndarray'>


In [58]:
x = np.random.choice([9, 3, 7, 5])
print(x)

3


In [59]:
x = np.random.choice([9, 3, 7, 5], size=(3, 5)) # sampling to create an nd-array
print(x)
print(type(x))

[[7 5 3 9 7]
 [3 3 7 3 5]
 [3 7 5 9 9]]
<class 'numpy.ndarray'>
